### 
GET http://localhost:4000/join/read

### 
GET http://localhost:4000/join/read/1

###
POST http://localhost:4000/join/create
Content-Type: application/json

{
    "storages": 5,
    "items": [10, 11]
}

###
PUT http://localhost:4000/join/update/1
Content-Type: application/json

{
    "storages": 1,
    "items": [2]
}

### 
DELETE http://localhost:4000/join/delete/5